### ISSUE TITLE
Can't select latest version of Amplified Bible

### ISSUE THREAD

**Issue by bevanjkay** [caleb531/youversion-suggest-data#1]
Hey @caleb531,
I'm having an issue with not being able to select AMP15 or just AMP as the translation in the module.

For example (my keyword is "bible");
bible 1 john 4:9 AMP
Returns from the AMPC not the AMP.

**Comment by bevanjkay** [comment]
I have temporarily updated my data files to use the name "AMP15" for the Amplified Bible and it is working for now.

**Comment by caleb531** [comment]
@bevanjkay I can confirm the issue is reproducible on my end, and understand exactly why it's happening.

I will start thinking about the best way to solve this, as there are several different routes I could take. I'll post any updates here.

**Comment by caleb531** [comment]
@bevanjkay I've just released YouVersion Suggest v11.4.0 with the fix. Please try it out and let me know how it works for you:

https://github.com/caleb531/youversion-suggest-alfred/releases/tag/v11.4.0

**Comment by bevanjkay** [comment]
@caleb531 Issue is fixed. Thanks for the quick resolution. It's a great workflow!
